//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneNumber
    {
        public long Num { get; set; }
        public Nullable<long> ClientId { get; set; }
        public Nullable<int> TariffId { get; set; }
        public decimal Balance { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Tariff Tariff { get; set; }
    }
}
